services:
  postgres:
    image: postgres:12
    container_name: fastapi-app-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
  app:
    build: .
    container_name: fastapi-app
    command: ["/usr/local/bin/run.sh"]
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
